"""
evaluator.py
============
Evaluates performance metrics (parameter counts, FLOPs, and activation sizes)
of generated neural network architectures.
"""

from typing import List, Dict, Any

class ModelPerformanceEvaluator:
    """Evaluates computational footprint of search-selected layers."""
    
    def __init__(self, layers: List[str], input_dim: int = 128):
        """
        Args:
            layers: List of selected layer names.
            input_dim: Feature dimension size.
        """
        self.layers = layers
        self.dim = input_dim

    def profile(self) -> Dict[str, Any]:
        """
        Computes parameter and floating point operation (FLOP) estimates.
        
        Returns:
            Dictionary containing model diagnostic metrics.
        """
        total_flops = 0
        total_params = 0
        
        for layer in self.layers:
            if layer == "LinearProjection":
                # Projection mapping (dim -> dim)
                params = self.dim * self.dim + self.dim
                flops = 2 * self.dim * self.dim
                
            elif layer == "ConvolutionalBlock":
                # Standard Conv 3x3 on 2D space (assume 32x32 feature map)
                kernel_ops = 3 * 3 * self.dim * self.dim
                params = kernel_ops + self.dim
                flops = kernel_ops * 32 * 32
                
            elif layer == "AttentionBlock":
                # Multi-head attention (Query, Key, Value mappings + softmax scaling)
                qkv_params = 3 * (self.dim * self.dim + self.dim)
                out_proj = self.dim * self.dim + self.dim
                params = qkv_params + out_proj
                
                # Assume sequence length L=64
                seq_len = 64
                flops = (qkv_params + out_proj) * seq_len + 2 * (seq_len ** 2) * self.dim
                
            elif layer == "ResidualBlock":
                # 2x Linear projections + elementwise add
                params = 2 * (self.dim * self.dim + self.dim)
                flops = 2 * (2 * self.dim * self.dim)
                
            elif layer == "LayerNorm":
                # Scale and shift parameters
                params = 2 * self.dim
                flops = 4 * self.dim
                
            else:
                params = 0
                flops = 0
                
            total_params += params
            total_flops += flops
            
        return {
            "parameter_count": total_params,
            "estimated_flops": total_flops,
            "input_dimension": self.dim,
            "layer_count": len(self.layers)
        }

    def generate_pytorch_stub(self) -> str:
        """
        Generates PyTorch model source code corresponding to the search output.
        
        Returns:
            A string containing the PyTorch class definition.
        """
        code = [
            "import torch",
            "import torch.nn as nn",
            "",
            "class AutoGeneratedModel(nn.Module):",
            f"    def __init__(self, input_dim={self.dim}):",
            "        super().__init__()",
            "        self.layers = nn.ModuleList()",
            "        # Layer stack:"
        ]
        
        for idx, layer in enumerate(self.layers):
            if layer == "LinearProjection":
                code.append(f"        self.layers.append(nn.Linear(input_dim, input_dim))")
            elif layer == "ConvolutionalBlock":
                # Channel mapping representation
                code.append(f"        self.layers.append(nn.Conv2d(input_dim, input_dim, kernel_size=3, padding=1))")
            elif layer == "AttentionBlock":
                code.append(f"        self.layers.append(nn.MultiheadAttention(embed_dim=input_dim, num_heads=4))")
            elif layer == "ResidualBlock":
                # Sequential approximation
                code.append(f"        self.layers.append(nn.Sequential(nn.Linear(input_dim, input_dim), nn.ReLU(), nn.Linear(input_dim, input_dim)))")
            elif layer == "LayerNorm":
                code.append(f"        self.layers.append(nn.LayerNorm(input_dim))")
                
        code.extend([
            "",
            "    def forward(self, x):",
            "        # Execution path",
            "        for layer in self.layers:",
            "            if isinstance(layer, nn.Conv2d):",
            "                # Shape transform: assume input is (B, C, H, W) for Conv",
            "                if len(x.shape) == 2:",
            "                    # Add spatial dimensions for compatibility",
            "                    x_sp = x.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, 8, 8)",
            "                    x = layer(x_sp).mean(dim=[-1, -2])",
            "                else:",
            "                    x = layer(x)",
            "            elif isinstance(layer, nn.MultiheadAttention):",
            "                # Query, Key, Value projection (sequence dimension)",
            "                if len(x.shape) == 2:",
            "                    # Make sequence shape (1, B, C)",
            "                    x_seq = x.unsqueeze(0)",
            "                    x_seq, _ = layer(x_seq, x_seq, x_seq)",
            "                    x = x_seq.squeeze(0)",
            "                else:",
            "                    x, _ = layer(x, x, x)",
            "            else:",
            "                x = layer(x)",
            "        return x"
        ])
        
        return "\n".join(code)
