import pytest
import os
import tempfile
from pathlib import Path
from nas_graph.parser import CodebaseASTParser
from nas_graph.search import ArchitectureSearchEngine
from nas_graph.evaluator import ModelPerformanceEvaluator

def test_ast_parser_complexity():
    # Create temporary python files to scan
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create file A
        file_a = Path(tmpdir) / "file_a.py"
        file_a.write_text("""
class BaseClassifier:
    def __init__(self):
        pass

def process_features(x):
    y = x + 1
    return y
""", encoding="utf-8")

        # Create file B
        file_b = Path(tmpdir) / "file_b.py"
        file_b.write_text("""
from file_a import BaseClassifier
class AdvancedClassifier(BaseClassifier):
    def run_inference(self):
        val = process_features(10)
        print(val)
""", encoding="utf-8")

        parser = CodebaseASTParser(tmpdir)
        graph = parser.scan()
        summary = parser.get_summary_metrics()
        
        # Verify ast counts
        assert summary["total_files"] == 2
        assert summary["total_classes"] == 2
        assert summary["total_functions"] == 3
        assert summary["mean_complexity"] > 0
        assert "AdvancedClassifier" in graph
        assert "BaseClassifier" in graph["AdvancedClassifier"]

def test_architecture_search_constraints():
    metrics = {
        "total_files": 5,
        "total_classes": 3,
        "total_functions": 10,
        "mean_complexity": 8.0
    }
    engine = ArchitectureSearchEngine(metrics)
    
    # Tight constraints
    res_tight = engine.search(max_latency_ms=0.5, max_params_million=0.2)
    assert res_tight["estimated_latency_ms"] <= 0.5
    assert res_tight["estimated_params_million"] <= 0.2
    
    # Loose constraints
    res_loose = engine.search(max_latency_ms=10.0, max_params_million=5.0)
    assert len(res_loose["layers"]) >= 4

def test_performance_evaluator():
    layers = ["LinearProjection", "AttentionBlock", "LayerNorm"]
    evaluator = ModelPerformanceEvaluator(layers, input_dim=64)
    profile = evaluator.profile()
    
    assert profile["layer_count"] == 3
    assert profile["parameter_count"] > 0
    assert profile["estimated_flops"] > 0
    assert profile["input_dimension"] == 64
    
    # Check PyTorch stub generation
    stub = evaluator.generate_pytorch_stub()
    assert "class AutoGeneratedModel(nn.Module):" in stub
    assert "nn.Linear" in stub
    assert "nn.MultiheadAttention" in stub
